export const actionTypes = {
  SET_LOAD_STATUS: 'SET_LOAD_STATUS',
  SET_PROPERTIES_SUCCESS: 'SET_PROPERTIES_SUCCESS',
  SET_PROPERTIES_ERROR: 'SET_PROPERTIES_ERROR',
  SET_PROPERTIES_LOADING: 'SET_PROPERTIES_LOADING',
};
