export const SET_LOAD_STATUS = 'SET_LOAD_STATUS';
export const SET_PROPERTIES_STATUS = 'SET_PROPERTIES_STATUS';
export const SET_PROPERTIES_ERROR = 'SET_PROPERTIES_ERROR';
export const SET_PROPERTIES = 'SET_PROPERTIES';
export const SET_PROPERTY_LOAD_STATUS = 'SET_PROPERTY_LOAD_STATUS';
